repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml  # Check YAML file syntax
      - id: check-added-large-files  # Prevent committing large files
        args: ["--maxkb=500"]  # Set maximum file size to 500 KB

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the latest version
    hooks:
      - id: mypy
        language_version: python3.11

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0  # Use the latest version
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5  # Use the latest version
    hooks:
      - id: bandit
        args: ["--skip", "B101"]  # Skip assert usage check

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0  # Use the latest version
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json  # Validates JSON syntax
      - id: check-xml  # Validates XML syntax
      - id: check-added-large-files  # Already added, keeping it for consistency
        args: ["--maxkb=500"]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.5  # Use the latest version
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the latest version
    hooks:
      - id: mypy
        args:
          - "--strict"  # Enable strict checks

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest version
    hooks:
      - id: black
        args:
          - "--check"  # Verify formatting but don't apply changes
